# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgis/postgis
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  postgres:
    name: nest-init-docker-db
