GET http://localhost:3001/markets?long=180&lat=90&limit=10&radiusInKm=30000

###
POST http://localhost:3001/markets/
Content-Type: application/json

{
    "name": "Sesame Street's Market POST test",
    "teaser": "Fresh produce and artisanal apparel",
    "address": "Sesame Street 12",
    "city": "Philadelphia",
    "country": "US",
    "location": {
        "lat": 12.34,
        "long": 23.45
    },
    "products": ["Cheese", "Dairy", "Textile", "Flax"],
    "state": "PA",
    "zip": "12345"
}

### Market Image upload

POST http://localhost:3001/markets/a460fe2d-cec3-4330-baf9-61f8f6229794/image-upload HTTP/1.1
Content-Type: multipart/form-data; boundary=MfnBoundry

--MfnBoundry
Content-Disposition: form-data; name="imageDescription"
Content-Type: text/plain

Test image showing the number zero
--MfnBoundry
Content-Disposition: form-data; name="file"; filename="test2.jpg"
Content-Type: image/jpeg

< ./test/test.jpg
--MfnBoundry--