name: deploy
on:
  push:
    branches: [main]

env:
  TAG_SUFFIX: latest
  TAG_REPO: farmers-market-finder
  ECR_REGISTRY_BASE: 756399734264.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY_SUFFIX: repo-3c58070

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Build and Package Docker Image
        run: |

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY_BASE}

          docker build --target production -t ${TAG_REPO}:${TAG_SUFFIX} .
          TAG_ID=$(docker images -q ${TAG_REPO}:${TAG_SUFFIX})
          docker tag $TAG_ID ${ECR_REGISTRY_BASE}/${ECR_REPOSITORY_SUFFIX}:${TAG_SUFFIX}
          docker push ${ECR_REGISTRY_BASE}/${ECR_REPOSITORY_SUFFIX}:${TAG_SUFFIX}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
